### ISSUE TITLE
text shadow

### ISSUE THREAD

**Issue by MarissaWood** [Tkaldahl/Tay-Tower-Game#6]
If the shadow is the same for all four headings you can put them all into one

```css
h1, h2, h3, h4, {
text-shadow: 3px 1px #bf584d;
}
```
https://github.com/Tkaldahl/Tay-Tower-Game/blob/70fcb0ccf56358d99d24b22c0853a689f86152fd/style.css#L16-L38
